//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo_csharp.CustomerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.xsd.com", ConfigurationName="CustomerService.ICustomerServicePortType")]
    public interface ICustomerServicePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string QueryPayInfo(string CustomerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> QueryPayInfoAsync(string CustomerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string QueryCardById(string CustomerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> QueryCardByIdAsync(string CustomerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string QueryCards(string queryType, string queryParam1, string queryParam2, string queryParam3);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> QueryCardsAsync(string queryType, string queryParam1, string queryParam2, string queryParam3);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerServicePortTypeChannel : demo_csharp.CustomerService.ICustomerServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServicePortTypeClient : System.ServiceModel.ClientBase<demo_csharp.CustomerService.ICustomerServicePortType>, demo_csharp.CustomerService.ICustomerServicePortType {
        
        public CustomerServicePortTypeClient() {
        }
        
        public CustomerServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string QueryPayInfo(string CustomerId) {
            return base.Channel.QueryPayInfo(CustomerId);
        }
        
        public System.Threading.Tasks.Task<string> QueryPayInfoAsync(string CustomerId) {
            return base.Channel.QueryPayInfoAsync(CustomerId);
        }
        
        public string QueryCardById(string CustomerId) {
            return base.Channel.QueryCardById(CustomerId);
        }
        
        public System.Threading.Tasks.Task<string> QueryCardByIdAsync(string CustomerId) {
            return base.Channel.QueryCardByIdAsync(CustomerId);
        }
        
        public string QueryCards(string queryType, string queryParam1, string queryParam2, string queryParam3) {
            return base.Channel.QueryCards(queryType, queryParam1, queryParam2, queryParam3);
        }
        
        public System.Threading.Tasks.Task<string> QueryCardsAsync(string queryType, string queryParam1, string queryParam2, string queryParam3) {
            return base.Channel.QueryCardsAsync(queryType, queryParam1, queryParam2, queryParam3);
        }
    }
}
