//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Web Services Description Language Utility
//Mono Framework v2.0.50727.5485
//
namespace WZ_N_SMS
{
    using System.Xml.Serialization;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Diagnostics;
    using System.Configuration;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "SmsHttpBinding", Namespace = "http://ws.flaginfo.com.cn")]
    public partial class WZ_Sms : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback CallSmsOperationCompleted;

        private System.Threading.SendOrPostCallback ReportOperationCompleted;

        private System.Threading.SendOrPostCallback ReplyOperationCompleted;

        private System.Threading.SendOrPostCallback ReplyConfirmOperationCompleted;

        private System.Threading.SendOrPostCallback SearchSmsNumOperationCompleted;

        private System.Threading.SendOrPostCallback AuditingOperationCompleted;

        /// <remarks/>
        public WZ_Sms()
        {
            string DXAddress = "http://api.ums86.com:8888/sms_hb/services/Sms?wsdl";
            this.Url = DXAddress;
            //this.Url = url;
        }

        /// <remarks/>
        public event CallSmsCompletedEventHandler CallSmsCompleted;

        /// <remarks/>
        public event ReportCompletedEventHandler ReportCompleted;

        /// <remarks/>
        public event ReplyCompletedEventHandler ReplyCompleted;

        /// <remarks/>
        public event ReplyConfirmCompletedEventHandler ReplyConfirmCompleted;

        /// <remarks/>
        public event SearchSmsNumCompletedEventHandler SearchSmsNumCompleted;

        /// <remarks/>
        public event AuditingCompletedEventHandler AuditingCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestElementName = "Sms", RequestNamespace = "http://ws.flaginfo.com.cn", ResponseElementName = "SmsResponse", ResponseNamespace = "http://ws.flaginfo.com.cn", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable = true)]
        public string CallSms([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string in3, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string in4, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string in5, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string in6, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string in7, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string in8, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string in9, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string in10)
        {
            object[] results = this.Invoke("CallSms", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6,
                        in7,
                        in8,
                        in9,
                        in10});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void CallSmsAsync(string in0, string in1, string in2, string in3, string in4, string in5, string in6, string in7, string in8, string in9, string in10)
        {
            this.CallSmsAsync(in0, in1, in2, in3, in4, in5, in6, in7, in8, in9, in10, null);
        }

        /// <remarks/>
        public void CallSmsAsync(string in0, string in1, string in2, string in3, string in4, string in5, string in6, string in7, string in8, string in9, string in10, object userState)
        {
            if ((this.CallSmsOperationCompleted == null))
            {
                this.CallSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallSmsOperationCompleted);
            }
            this.InvokeAsync("CallSms", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4,
                        in5,
                        in6,
                        in7,
                        in8,
                        in9,
                        in10}, this.CallSmsOperationCompleted, userState);
        }

        private void OnCallSmsOperationCompleted(object arg)
        {
            if ((this.CallSmsCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallSmsCompleted(this, new CallSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace = "http://ws.flaginfo.com.cn", ResponseNamespace = "http://ws.flaginfo.com.cn", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable = true)]
        public string Report([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string in2)
        {
            object[] results = this.Invoke("Report", new object[] {
                        in0,
                        in1,
                        in2});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void ReportAsync(string in0, string in1, string in2)
        {
            this.ReportAsync(in0, in1, in2, null);
        }

        /// <remarks/>
        public void ReportAsync(string in0, string in1, string in2, object userState)
        {
            if ((this.ReportOperationCompleted == null))
            {
                this.ReportOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReportOperationCompleted);
            }
            this.InvokeAsync("Report", new object[] {
                        in0,
                        in1,
                        in2}, this.ReportOperationCompleted, userState);
        }

        private void OnReportOperationCompleted(object arg)
        {
            if ((this.ReportCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReportCompleted(this, new ReportCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestElementName = "ReplyRequest", RequestNamespace = "http://ws.flaginfo.com.cn", ResponseNamespace = "http://ws.flaginfo.com.cn", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result", IsNullable = true)]
        public string Reply([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string in3, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] out string confirm_time, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] out string id, [System.Xml.Serialization.XmlElementAttribute("replys", IsNullable = true)] out Reply[] replys)
        {
            object[] results = this.Invoke("Reply", new object[] {
                        in0,
                        in1,
                        in2,
                        in3});
            confirm_time = ((string)(results[1]));
            id = ((string)(results[2]));
            replys = ((Reply[])(results[3]));
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void ReplyAsync(string in0, string in1, string in2, string in3)
        {
            this.ReplyAsync(in0, in1, in2, in3, null);
        }

        /// <remarks/>
        public void ReplyAsync(string in0, string in1, string in2, string in3, object userState)
        {
            if ((this.ReplyOperationCompleted == null))
            {
                this.ReplyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReplyOperationCompleted);
            }
            this.InvokeAsync("Reply", new object[] {
                        in0,
                        in1,
                        in2,
                        in3}, this.ReplyOperationCompleted, userState);
        }

        private void OnReplyOperationCompleted(object arg)
        {
            if ((this.ReplyCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReplyCompleted(this, new ReplyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestElementName = "ReplyConfirmRequest", RequestNamespace = "http://ws.flaginfo.com.cn", ResponseNamespace = "http://ws.flaginfo.com.cn", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result", IsNullable = true)]
        public string ReplyConfirm([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string in3, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string in4)
        {
            object[] results = this.Invoke("ReplyConfirm", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void ReplyConfirmAsync(string in0, string in1, string in2, string in3, string in4)
        {
            this.ReplyConfirmAsync(in0, in1, in2, in3, in4, null);
        }

        /// <remarks/>
        public void ReplyConfirmAsync(string in0, string in1, string in2, string in3, string in4, object userState)
        {
            if ((this.ReplyConfirmOperationCompleted == null))
            {
                this.ReplyConfirmOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReplyConfirmOperationCompleted);
            }
            this.InvokeAsync("ReplyConfirm", new object[] {
                        in0,
                        in1,
                        in2,
                        in3,
                        in4}, this.ReplyConfirmOperationCompleted, userState);
        }

        private void OnReplyConfirmOperationCompleted(object arg)
        {
            if ((this.ReplyConfirmCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReplyConfirmCompleted(this, new ReplyConfirmCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestElementName = "SearchSmsNumRequest", RequestNamespace = "http://ws.flaginfo.com.cn", ResponseNamespace = "http://ws.flaginfo.com.cn", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("result", IsNullable = true)]
        public string SearchSmsNum([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] out string number)
        {
            object[] results = this.Invoke("SearchSmsNum", new object[] {
                        in0,
                        in1,
                        in2});
            number = ((string)(results[1]));
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void SearchSmsNumAsync(string in0, string in1, string in2)
        {
            this.SearchSmsNumAsync(in0, in1, in2, null);
        }

        /// <remarks/>
        public void SearchSmsNumAsync(string in0, string in1, string in2, object userState)
        {
            if ((this.SearchSmsNumOperationCompleted == null))
            {
                this.SearchSmsNumOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchSmsNumOperationCompleted);
            }
            this.InvokeAsync("SearchSmsNum", new object[] {
                        in0,
                        in1,
                        in2}, this.SearchSmsNumOperationCompleted, userState);
        }

        private void OnSearchSmsNumOperationCompleted(object arg)
        {
            if ((this.SearchSmsNumCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchSmsNumCompleted(this, new SearchSmsNumCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestElementName = "AuditingRequest", RequestNamespace = "http://ws.flaginfo.com.cn", ResponseNamespace = "http://ws.flaginfo.com.cn", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("out", IsNullable = true)]
        public string Auditing([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string in0, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string in1, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string in2, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string in3)
        {
            object[] results = this.Invoke("Auditing", new object[] {
                        in0,
                        in1,
                        in2,
                        in3});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void AuditingAsync(string in0, string in1, string in2, string in3)
        {
            this.AuditingAsync(in0, in1, in2, in3, null);
        }

        /// <remarks/>
        public void AuditingAsync(string in0, string in1, string in2, string in3, object userState)
        {
            if ((this.AuditingOperationCompleted == null))
            {
                this.AuditingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuditingOperationCompleted);
            }
            this.InvokeAsync("Auditing", new object[] {
                        in0,
                        in1,
                        in2,
                        in3}, this.AuditingOperationCompleted, userState);
        }

        private void OnAuditingOperationCompleted(object arg)
        {
            if ((this.AuditingCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuditingCompleted(this, new AuditingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ws.flaginfo.com.cn")]
    public partial class Reply
    {

        private string callMdnField;

        private string mdnField;

        private string contentField;

        private string reply_timeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string callMdn
        {
            get
            {
                return this.callMdnField;
            }
            set
            {
                this.callMdnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string mdn
        {
            get
            {
                return this.mdnField;
            }
            set
            {
                this.mdnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string content
        {
            get
            {
                return this.contentField;
            }
            set
            {
                this.contentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string reply_time
        {
            get
            {
                return this.reply_timeField;
            }
            set
            {
                this.reply_timeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    public delegate void CallSmsCompletedEventHandler(object sender, CallSmsCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CallSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    public delegate void ReportCompletedEventHandler(object sender, ReportCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    public delegate void ReplyCompletedEventHandler(object sender, ReplyCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReplyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ReplyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }

        /// <remarks/>
        public string confirm_time
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }

        /// <remarks/>
        public string id
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }

        /// <remarks/>
        public Reply[] replys
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((Reply[])(this.results[3]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    public delegate void ReplyConfirmCompletedEventHandler(object sender, ReplyConfirmCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReplyConfirmCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ReplyConfirmCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    public delegate void SearchSmsNumCompletedEventHandler(object sender, SearchSmsNumCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchSmsNumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal SearchSmsNumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }

        /// <remarks/>
        public string number
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    public delegate void AuditingCompletedEventHandler(object sender, AuditingCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "0.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuditingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal AuditingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
